services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vendas-app
    ports:
      - '3030:3000'
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    depends_on:
      - db

  db:
    image: mariadb:10.3
    container_name: "c-mysql-vendas-app"
    environment:
      MYSQL_ROOT_PASSWORD: bsi-vendas
    ports:
      - "3031:3306"
    volumes:
      - ./data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "c-phpmyadmin-vendas-app"
    environment:
      MYSQL_ROOT_PASSWORD: bsi-vendas
    ports:
      - "3032:80"